apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 194768394447.dkr.ecr.us-east-1.amazonaws.com/workshop-2/production/backend
        ports:
        - containerPort: 80
